@startuml 02_kanban

title "Канбан"

!include common.puml

box "Data"
  database Data
  collections "Data\n.goals"          as d.goals
  collections "Data\n.projects"       as d.projects
  collections "Data\n.tasks"          as d.tasks
  collections "Data\n.checklists"     as d.checklists
  collections "Data\n.checklistItems" as d.items
  collections "Data\n.contexts"       as d.contexts
  
end box
box "Kanban"
  participant Kanban             as Kanban
  participant "[Kanban\n.FOLDERS]" as k.folders
  participant .filter            as k.filter
  participant .content           as k.content
end box
participant Folder as Folder
participant TaskFactory as TaskFactory
participant Task
participant Checklist
participant ChecklistItem

== Создание ==

Kanban -> k.filter : Это позже

loop Kanban.FOLDERS as f
  Kanban -> Folder : new Folder(f)
  group Получить данные для задач типов "Задача" и "Чеклист"
    Folder -> d.tasks --++ <<request>> : filter(f.ID)
    d.tasks -> Folder -- <<link>> : .tasksData += [ taskData ]
    Folder -> d.checklists --++ <<request>> : filter(f.ID)
    d.checklists -> Folder -- <<link>> : .tasksData +=[ taskData ]
  end

  loop tasksData as td
    Folder -> TaskFactory : TaskAbstract.get(td)
    alt td.TYPE == TASK
      TaskFactory -> Task ++ : new Task(td)
      Task -> TaskFactory -- <<link>> : task
    else td.TYPE == CHECKLIST
      TaskFactory -> Checklist ++ : new Checklist(td)
      Checklist -> TaskFactory -- <<link>> : task
    end
    TaskFactory -> Folder <<link>> : .tasks += task
  end
end


@enduml